### PR TITLE
test(docs): runnable doctest for core engine flow (#121)

### LINKED ISSUE #121: [super-qa] medium: zero runnable doc-tests in crate
## Finding: All Doc Examples Use rust,ignore

- **ID:** M24
- **Severity:** medium
- **Category:** testing
- **Location:** src/async_engine.rs:28-33, src/search/query.rs:17-32

## Description

The crate has exactly 2 doc examples, both marked \`\`\`rust,ignore\`\`\`. No public API type has runnable doc-tests. MemoryEngine has 40+ public methods with zero doc-test coverage.

## Suggested Approach

Convert at least the \`MemoryEngine::open_memory + add_fact + query\` flow to a runnable doc-test.

### LINKED ISSUE #564: fix(cli): cli_integration test calls removed MemoryEngine::open (broken since #556)
## Summary

`memory-engine-cli/tests/cli_integration.rs:124` still calls the removed `MemoryEngine::open(&config)` constructor, so the `cli_integration` test target **fails to compile**, breaking `cargo test --workspace`.

```
error[E0599]: no associated function or constant named `open` found for struct `MemoryEngine`
   --> memory-engine-cli/tests/cli_integration.rs:124:47
```

## Root cause

PR #556 (`refactor(core)!: replace telescoping MemoryEngine constructors with a typestate builder`) removed the `MemoryEngine::open(&EngineConfig)` constructor in favor of the typestate builder. It updated most call sites (e.g. `cli_integration.rs:12` and `:239` already use `MemoryEngine::builder(4).path(..).build()`), but missed line 124 inside `stats_plain_includes_max_depth_and_page_count`.

## Fix

Replace the stale call:

```rust
// before
let config = memory_engine::EngineConfig::new(db_path.clone(), 4);
let engine = memory_engine::MemoryEngine::open(&config).unwrap();

// after
let engine = memory_engine::MemoryEngine::builder(4)
    .path(db_path.clone())
    .build()
    .unwrap();
```

## Scope

Pre-existing on `origin/main`; discovered as collateral while implementing #130 (engine-level error-path tests). Out of scope for that PR (test-only, core crate). The core/mcp/embed crates all build and test cleanly; only this one CLI integration-test target is broken.

### LINKED ISSUE #569: fix(cli): cli_integration test calls removed MemoryEngine::open constructor
## Finding

`cargo test --workspace` fails to **compile** the CLI integration test target:

\`\`\`
error[E0599]: no associated function or constant named \`open\` found for struct \`MemoryEngine\`
   --> memory-engine-cli/tests/cli_integration.rs:124:47
124 |     let engine = memory_engine::MemoryEngine::open(&config).unwrap();
\`\`\`

## Cause

The typestate-builder migration (#556) removed the telescoping `MemoryEngine::open*` constructors in favor of `MemoryEngine::builder(...).path(...).build()` and the `EngineConfig`-based `open_from_config` path. `memory-engine-cli/tests/cli_integration.rs:124` was not updated and still calls `MemoryEngine::open(&config)`, so the `memory-engine-cli` test target no longer compiles. This breaks the whole-workspace test gate (`cargo test --workspace`).

This is pre-existing on `main` (commit at time of filing: the `open` call is present verbatim in `git show main:memory-engine-cli/tests/cli_integration.rs`). It was surfaced while implementing #121 (runnable doctests) but is unrelated to that change — filed separately per the one-concern-per-issue contract.

## Fix

Replace the removed constructor with the current API. Given `config: EngineConfig`, the equivalent is the file-backed builder, e.g.:

\`\`\`rust
let engine = MemoryEngine::builder(config.embed_dim())
    .path(/* config path */)
    .build()
    .unwrap();
\`\`\`

or, if the test already has an `EngineConfig`, use the `EngineConfig`-consuming restore/open path that the builder dispatches to internally. Check `src/engine/restore.rs` and `src/engine/builder.rs` for the current entry points and pick the one matching the test's intent (fresh open vs. restore).

## Acceptance

- `cargo test --workspace` compiles and passes (no `E0599` on `MemoryEngine::open`).

### PR DESCRIPTION
**Pull request by dutiona**
## What

The crate had three `rust,ignore` doc examples and **no runnable doctest demonstrating the core `build -> add_fact -> query` flow** (issue #121, super-qa finding M24). Note: a couple of runnable doctests already existed (`engine/mod.rs` `EngineConfig`, `engine/builder.rs`), but none covered the end-to-end round-trip on a prominent public item.

This adds a self-contained, deterministic doctest on the crate-level `//!` and converts two of the three `ignore` examples into runnable ones, all driven by the typestate `MemoryEngine::builder` (#556):

- **`src/lib.rs` (`//!`)** — new quick-start: in-memory `MemoryEngine::builder(dim)` -> `add_fact` -> `execute_query(MemoryQuery::new().text(...))`, asserting the round-tripped fact content.
- **`src/async_engine.rs`** — the `AsyncMemoryEngine` example now runs on a real tokio runtime with an `Arc<dyn EmbeddingProvider + Send + Sync>` (executes under `--all-features`), and reads the fact back via `get_fact` to prove the `spawn_blocking` round-trip actually persists (not just that an id was returned).
- **`src/search/query.rs`** — the `MemoryQuery` example builds an engine, ingests a fact under the **multi-segment** scope `user:michael/project:demo`, and asserts on `scope_subtree("user:michael")` retrieval, genuinely exercising depth > 1 hierarchical resolution.

Each example wires a tiny dependency-free `HashEmbedder` (bag-of-bytes into a fixed dim) so it is deterministic and needs no model or network — true to the crate's "zero LLM/network deps" contract.

The third `ignore` (`src/resume/context.rs`) stays `ignore` with its existing inline reason: it documents a `pub(crate)` helper that a compiled doctest cannot reach from outside the crate.

## Bug fix (surfaced by the doctest work)

Writing the multi-segment scope example exposed a real latent bug: `ensure_scope_with_conn` cached only the **leaf** scope node into the in-memory `ScopeTree`, not its ancestors. Since `resolve_path` walks `children` from the root, the missing intermediate links made any depth > 1 scope query (`scope_subtree`/`scope_exact`/…) return **zero results in-session**, even though the facts were persisted correctly.

Rather than dodge it with a single-segment scope, this PR fixes the root cause: walk leaf -> root via `parent_id` and cache the entire chain (idempotent, cycle-guarded). Pinned with a regression test `execute_query_subtree_multi_segment_scope`.

## Collateral: CLI test compile breakage (#564 / #569)

`memory-engine-cli/tests/cli_integration.rs:124` still called the removed `MemoryEngine::open(&config)` constructor (dropped by the typestate-builder migration #556), so `cargo test --workspace` failed to compile — a pre-existing breakage on `main`, tracked by #564 and #569. Migrated the call site to the builder pattern already used elsewhere in the same file, restoring the workspace gate.

## Gates

- `cargo test --doc` — 5 pass + 1 justified ignore (6 pass + 1 ignore under `--all-features`, including the async example).
- `cargo build --workspace` — clean.
- `cargo test --workspace` — green (CLI test now compiles).
- `cargo clippy --workspace --all-targets` — zero errors.
- `cargo fmt --check` — clean.

Closes #121
Closes #564
Closes #569

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by dutiona** [comment]
## Adversarial review summary (replaces /super-review)

Reviewed by **3 test-lens reviewers** + a **dedicated correctness review** of the bundled core fix.

| Lens        | Verdict                      | Note                                                                                                                                                                                 |
| ----------- | ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| does-it-run | 🔴→✅ **block → remediated** | doctests run under `cargo test --doc` (not `ignore`/`no_run`), deterministic inline `HashEmbedder`, mutation-tested discriminating — but **blocked** for silently dodging a real bug |
| coverage    | 🔴→✅ **block → remediated** | same blocker: a real `scope_subtree` defect was worked around instead of pinned                                                                                                      |
| correctness | ✅ minor                     | doctests use the current typestate builder correctly                                                                                                                                 |

**Remediation (the right call):** instead of just filing the bug, the agent **fixed it** — `ensure_scope_with_conn` cached only the _leaf_ scope node, so multi-segment `scope_subtree`/`scope_exact` returned 0; now caches the full ancestor chain (cycle-guarded) + regression test `execute_query_subtree_multi_segment_scope`. It also migrated `cli_integration.rs` off the removed `MemoryEngine::open` (fixes #564, unblocking `cargo test --workspace`).

**Dedicated review of the (remediation-introduced, previously unreviewed) scope fix → ✅ APPROVE:** verified the leaf→root walk caches ancestors correctly (root already in tree, no off-by-one), the cycle guard (`HashSet seen` + root + `parent_id`) is sound (no loop/overflow), edge cases (single-segment, root, cross-session, deep) hold, and the regression test is discriminating. **661 lib + 61 scope + 25 tree tests pass.**

> Scope note: this PR bundles #121 (doctest) + a `fix(core)` scope-resolution fix + the #564 CLI fix — all surfaced by the doctest work. Re-titled + documented accordingly.
