### ISSUE TITLE
fix(cli): cli_integration test calls removed MemoryEngine::open (broken since #556)

### ISSUE THREAD

**Issue by dutiona** [dutiona/memory-engine#564]
## Summary

`memory-engine-cli/tests/cli_integration.rs:124` still calls the removed `MemoryEngine::open(&config)` constructor, so the `cli_integration` test target **fails to compile**, breaking `cargo test --workspace`.

```
error[E0599]: no associated function or constant named `open` found for struct `MemoryEngine`
   --> memory-engine-cli/tests/cli_integration.rs:124:47
```

## Root cause

PR #556 (`refactor(core)!: replace telescoping MemoryEngine constructors with a typestate builder`) removed the `MemoryEngine::open(&EngineConfig)` constructor in favor of the typestate builder. It updated most call sites (e.g. `cli_integration.rs:12` and `:239` already use `MemoryEngine::builder(4).path(..).build()`), but missed line 124 inside `stats_plain_includes_max_depth_and_page_count`.

## Fix

Replace the stale call:

```rust
// before
let config = memory_engine::EngineConfig::new(db_path.clone(), 4);
let engine = memory_engine::MemoryEngine::open(&config).unwrap();

// after
let engine = memory_engine::MemoryEngine::builder(4)
    .path(db_path.clone())
    .build()
    .unwrap();
```

## Scope

Pre-existing on `origin/main`; discovered as collateral while implementing #130 (engine-level error-path tests). Out of scope for that PR (test-only, core crate). The core/mcp/embed crates all build and test cleanly; only this one CLI integration-test target is broken.
