### ISSUE TITLE
Deferred: Determinism guarantees — replay, merge, idempotency rules

### ISSUE THREAD

**Issue by dutiona** [dutiona/memory-engine#19]
## What it solves

Crisp, documented rules for deterministic event replay, multi-device merge ordering, clock skew handling, and idempotent event application. Required for CRDT sync correctness.

## Trigger

Before sync work begins (prerequisite for SaaS Sync, issue #15).

## Scope

- Replay determinism: given the same event log, produce identical materialized state
- Merge ordering: deterministic interleaving of events from multiple origin_node_ids
- Clock skew: advisory timestamps must not affect correctness (only UX/debugging)
- Idempotency: applying the same event twice produces the same state (safe retries)
- Edge cases: concurrent expiry of same fact from different devices, conflicting consolidation results

## What it does NOT solve

- Does not implement sync itself (that's issue #15)
- Does not handle Byzantine fault tolerance (assumes honest but possibly out-of-order devices)

## Hints

- GPT-5.4 identified this as a blind spot
- Phase 3b adds origin_node_id + sequence_id to event envelope — enables per-origin ordering
- CRDT approach: each device's event stream is totally ordered (sequence_id); merge is union with causal ordering
- ConflictArbiter trait already handles semantic conflicts — need to extend to cross-device conflicts

## Design doc

See `docs/plans/2026-03-09-future-phases-design.md` — Deferred Items, GPT-5.4 Blind Spots
